-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, CITY||' '||STREET_ADDRESS1||' '||STREET_ADDRESS2 전체주소, 
SUBSTR(TLNO, 0,3)||'-'||SUBSTR(TLNO, 4, 4)||'-'||SUBSTR(TLNO, 8,4) 전화번호
FROM 
(SELECT WRITER_ID
FROM USED_GOODS_BOARD
GROUP BY WRITER_ID
HAVING COUNT(WRITER_ID) >= 3) A,
USED_GOODS_USER B
WHERE 1 = 1
AND A.WRITER_ID = B.USER_ID
ORDER BY USER_ID DESC