-- 코드를 입력하세요
SELECT CAR_ID, ROUND(AVG(DURATION), 1) AVERAGE_DURATION
FROM 
(SELECT CAR_ID, END_DATE - START_DATE+1 DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY)
GROUP BY CAR_ID
HAVING ROUND(AVG(DURATION), 1) >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC